[package]
name = "transaction-manifest"
version = "0.5.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor" }
scrypto = { path = "../scrypto" }
radix-engine = { path = "../radix-engine" }
clap = { version = "3.1.17", features = ["derive", "cargo"] }
hex = { version = "0.4.3" }