[package]
name = "scrypto-tests"
version = "0.5.0"
edition = "2021"

[dependencies]
scrypto = { path = "../scrypto", default-features = false }
sbor = { path = "../sbor", default-features = false }
serde = { version = "1.0.137", default-features = false }
serde_json = { version = "1.0.81", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto/std", "scrypto/serde", "sbor/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto/alloc", "scrypto/serde", "sbor/alloc"]